<?php

namespace ContainerMZRpx0g;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Sr7rCjzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sr7rCjz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sr7rCjz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'product' => ['privates', '.errored..service_locator.sr7rCjz.App\\Entity\\Article', NULL, 'Cannot autowire service ".service_locator.sr7rCjz": it references class "App\\Entity\\Article" but no such service exists.'],
        ], [
            'product' => 'App\\Entity\\Article',
        ]);
    }
}
