<?php

namespace ContainerMZRpx0g;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Qosw6frService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qosw6fr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qosw6fr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'ArticleRepository' => ['privates', 'App\\Repository\\ArticleRepository', 'getArticleRepositoryService', true],
        ], [
            'ArticleRepository' => 'App\\Repository\\ArticleRepository',
        ]);
    }
}
